
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Dashboard.module.css'


export default function Home() {
  return (
    
    
    <div >
      <Head>
        <title>SWENG 15 Dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
    <link
      rel="icon"
      href="https://cdn.glitch.global/c599d22a-c29e-49a0-8dd5-919bace7a532/%E2%80%94Pngtree%E2%80%94star%20vector%20icon_4015244.png?v=1668616941162"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
      </Head>

      
      <main className={styles.body}>
      <div className={styles.textblockA}>
      <div className={styles.header}>
        <div className={styles.dropdown}>
          <button className={styles.dropbtn}>
            Area
            <i className="fa fa-caret-down"></i>
          </button>
          <div className={styles.dropdowncontent}>
            <a href="dublin.html">Dublin</a>
            <a href="redmond.html">Redmond</a>
            <a href="sanfran.html">San Francisco</a>
            <a href="dehli.html">Dehli</a>
          </div>
        </div>
      </div>
    </div>
    </main>

    <h1>
      <div className={styles.icon}>
      DASHBOARD GROUP 15
      </div>
    </h1>

    </div>

  )
}
