
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dropdown from 'react-bootstrap/Dropdown';
import Link from 'next/link'

export default function Home() {
  

  return (
    
    <div className={styles.container}>
      <Head>
        <title>SWENG 15 Dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={styles.dropbtn }>
      <Dropdown>
      <Dropdown.Toggle variant="success" id="dropdown-basic">
        Navigate to Dashboard
      </Dropdown.Toggle>

      <Dropdown.Menu>
        <Dropdown.Item href="Dashboard">Dashboard</Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
    </div>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SWENG Group 15 Dashboard
         </h1>
         <h1 className={styles.title}>
          Go to <Link href="Dashboard">Dashboard</Link>

        </h1>

        

        
      </main>

      
    </div>
  )
}
