
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dropdown from 'react-bootstrap/Dropdown';
import Link from 'next/link'

export default function Home() {


  return (

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to SWENG Group 15 Dashboard
      </h1>
      <div className={styles.container}>
        <Head>
          <title>SWENG 15 Dasboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.dropdown}>
          <Dropdown>
            <Dropdown.Toggle variant="success" id="dropdown-basic">
              <div className={styles.dropbtn}>
                Navigate
              </div>
            </Dropdown.Toggle>

            <Dropdown.Menu className={styles.dropdowncontent}>
              <div className="dropdowncontent">
                <Dropdown.Item href="Dublin">Dublin</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="SanFrancisco">San Francisco</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="Delhi">Delhi</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="Redmond">Redmond</Dropdown.Item>
              </div>
            </Dropdown.Menu>
          </Dropdown>
        </div>
      </div>
    </main>
  )
}