
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  
  return (

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to SWENG Group 15 Dashboard
      </h1>
      <h2>(Select a city to view the dashboard)</h2>
      <div className={styles.container}>
        <Head>
          <title>SWENG 15 Dasboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </main>
  )
}