import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Dashboard.module.css'
import Dropdown from 'react-bootstrap/Dropdown';

export default function Home() {




  return (

    <main className={styles.main}>
      <div className={styles.container1}>
        <Head>
          <title>SWENG 15 Dasboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.dropdown}>
          <Dropdown>
            <Dropdown.Toggle variant="success" id="dropdown-basic">
              <div className={styles.dropbtn}>
                Navigate
              </div>
            </Dropdown.Toggle>

            <Dropdown.Menu className={styles.dropdowncontent}>
              <div className="dropdowncontent">
                <Dropdown.Item href="Dublin">Dublin</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="SanFrancisco">San Francisco</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="Delhi">Delhi</Dropdown.Item>
              </div>
              <div className="dropdowncontent">
                <Dropdown.Item href="Redmond">Redmond</Dropdown.Item>
              </div>
            </Dropdown.Menu>
          </Dropdown>
        </div>
      </div>


      <div className={styles.container}>
        <div className={styles.overimg1}>
          <form action="/action_page.php" className={styles.form}>
            <div className={styles.inputcontainer}>
              <i className="fa fa-calendar icon"></i>
              <input
                className={styles.inputfield}
                type="date"
                placeholder="Password"
                name="pswrd"
              />
            </div>

            <button
              type="submit"
              className={styles.btn}
              //onClick="check(this.form)"
              value="Login"
            >
              Input
            </button>
          </form>


        </div>
      </div>

    </main>


  )


}